<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to data analysis and visualization with R - 4&nbsp; Reading tabular data from disk</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_Basic_data_wrangling.html" rel="next">
<link href="./03_Functions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_Intro_R_RStudio.html">Part I: Processing and visualizing data with R</a></li><li class="breadcrumb-item"><a href="./04_Data_reading.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading tabular data from disk</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to data analysis and visualization with R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Part I: Processing and visualizing data with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Intro_R_RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_R_programming_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R programming basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Data_reading.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading tabular data from disk</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Basic_data_wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic data manipulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Summaries_normalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics and tidy data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Creating_figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Creating publication-grade figures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Further_plotting_options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Some further plotting options; introducing factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Joining_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Joining data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Part II: Introductory statistics (UNDER CONSTRUCTION)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_Intro_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introducing statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_Probabilities_and_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probabilities and probability distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Part III: Advanced statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40_Intro_adv_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introducing statistical inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41_Linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42_Anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">The Kruskal–Wallis test and one-way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43_Anova_two_way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Two-way ANOVA and the Scheirer–Ray–Hare test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44_Nonlinear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">More general linear models; nonlinear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45_Intro_map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Higher-order functions and mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./46_Multiple_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Nested data and multiple analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">References</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-tidyverse-package-suite" id="toc-the-tidyverse-package-suite" class="nav-link active" data-scroll-target="#the-tidyverse-package-suite"><span class="header-section-number">4.1</span> The <code>tidyverse</code> package suite</a></li>
  <li><a href="#data-file-formats" id="toc-data-file-formats" class="nav-link" data-scroll-target="#data-file-formats"><span class="header-section-number">4.2</span> Data file formats</a>
  <ul>
  <li><a href="#the-csv-file-format" id="toc-the-csv-file-format" class="nav-link" data-scroll-target="#the-csv-file-format"><span class="header-section-number">4.2.1</span> The CSV file format</a></li>
  <li><a href="#sec-snail" id="toc-sec-snail" class="nav-link" data-scroll-target="#sec-snail"><span class="header-section-number">4.2.2</span> The Galápagos land snail data</a></li>
  <li><a href="#tabulator-separated-and-other-delimited-files" id="toc-tabulator-separated-and-other-delimited-files" class="nav-link" data-scroll-target="#tabulator-separated-and-other-delimited-files"><span class="header-section-number">4.2.3</span> Tabulator-separated and other delimited files</a></li>
  </ul></li>
  <li><a href="#the-tibble-data-structure" id="toc-the-tibble-data-structure" class="nav-link" data-scroll-target="#the-tibble-data-structure"><span class="header-section-number">4.3</span> The <code>tibble</code> data structure</a></li>
  <li><a href="#sec-delim" id="toc-sec-delim" class="nav-link" data-scroll-target="#sec-delim"><span class="header-section-number">4.4</span> Reading delimited files</a></li>
  <li><a href="#sec-rename" id="toc-sec-rename" class="nav-link" data-scroll-target="#sec-rename"><span class="header-section-number">4.5</span> Naming (and renaming) columns</a></li>
  <li><a href="#sec-excel" id="toc-sec-excel" class="nav-link" data-scroll-target="#sec-excel"><span class="header-section-number">4.6</span> Excel tables</a></li>
  <li><a href="#writing-data-to-files" id="toc-writing-data-to-files" class="nav-link" data-scroll-target="#writing-data-to-files"><span class="header-section-number">4.7</span> Writing data to files</a></li>
  <li><a href="#sec-reading-exercises" id="toc-sec-reading-exercises" class="nav-link" data-scroll-target="#sec-reading-exercises"><span class="header-section-number">4.8</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-reading" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading tabular data from disk</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="the-tidyverse-package-suite" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-tidyverse-package-suite"><span class="header-section-number">4.1</span> The <code>tidyverse</code> package suite</h2>
<p>A suite of R packages, sharing the same design philosophy, are collected under the name <a href="https://www.tidyverse.org/"><code>tidyverse</code></a>. The <code>tidyverse</code> describes itself as “an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures.” The packages in this ecosystem work well together, making it easy to combine their elements to perform a wide range of data analysis tasks. In case it is not yet installed on your computer, type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>at the R console and press Enter. After the package is installed, we can load it via the function call</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Looking at the message generated by executing the above line, we see that nine packages are now loaded.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> They are called <code>ggplot2</code>, <code>tibble</code>, and so on. We will get to know these in more detail throughout the book.</p>
<p>There are even more packages that are part of the tidyverse. Typing and executing <code>tidyverse_packages()</code> will show all such packages. Of all these, only eight are loaded by default when invoking <code>library(tidyverse)</code>. The others must be loaded separately. For example, <code>readxl</code> is a tidyverse package for loading Excel files in R. To use it, run <code>library(readxl)</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In general, it is a good idea to load all necessary packages at the top of your R script, instead of loading them wherever the need to use them first arises. There are two reasons for this. First, if you close and then later reopen RStudio, the packages do not get automatically reloaded—one must execute the calls to <code>library</code> all over again. Second, often other users will run the scripts you write on their own computers, and they will not be able to do so unless the proper packages are loaded first. It is then helpful to others if the necessary packages are all listed right at the top, showing what is needed to run your program.</p>
</div>
</div>
</section>
<section id="data-file-formats" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="data-file-formats"><span class="header-section-number">4.2</span> Data file formats</h2>
<p>One of the packages loaded by default with the <code>tidyverse</code> is called <code>readr</code>. This package contains tools for loading data files and writing them to disk. We will explore how it works using an example dataset. Before turning to the data however, it is worth mentioning a few things about data file formats.</p>
<p><em>Tabular data</em> (i.e., data which can be organized into a table with rows and named columns) may be stored in many different forms. By far the most popular choice is to use Excel spreadsheets. While these may have many good properties, they are decidedly not recommended for scientific use. Instead, in science we strive to rely on <em>plain text files</em> to store our data. Plain text files have several advantages. First, they can be read by any machine without the need for special or proprietary software (such as Excel). Second, they will never go obsolete: one will always be able to open plain text files on any machine. By contrast, there is no guarantee that an Excel file saved today will still open ten years from now in future versions of Excel. And third, file formats such as Excel’s <code>.xls</code> and <code>.xlsx</code> contain a lot of metadata about formatting, font types, locale, etc. that are obscured from the user, but which have the potential to be in the way when performing scientific analyses. By contrast, plain text files have nothing up their sleeve: what you see they contain is exactly what you get; no more, no less. For these reasons, this book will emphasize workflows that rely on data stored in plain text files. However, due to the popularity of Excel, we will also learn how to read data from Excel files into R (<a href="#sec-excel"><span>Section&nbsp;4.6</span></a>), even though their use is otherwise not recommended.</p>
<section id="the-csv-file-format" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="the-csv-file-format"><span class="header-section-number">4.2.1</span> The CSV file format</h3>
<p>How can one store data in plain text files? There are various solutions, but the one we will be relying on is called a <em>delimited file</em>. These files contain information as in a spreadsheet, with contents from every row in a different line. The column entries are separated by some <em>delimiter</em>—a character that represents the end of the information in one column and the start of the next. As an example, let us consider some actual data on land snail species from the Galápagos Islands.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The data file is available by clicking on this link: <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-csv.zip"><code>islands-FL.csv</code></a>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Set the working directory in RStudio to the folder where you have saved it. As a reminder, one can do this by executing <code>setwd("/path/to/files")</code>, where one should substitute in one’s own path in place of <code>/path/to/files</code>. Then one can open <code>islands-FL.csv</code> in RStudio by clicking on it in the <strong>Files</strong> panel in the lower right part of the RStudio window, and then choosing the option “View file” (ignore the other option called “Import dataset…”). Having done this, a new tab opens in the editor panel (upper left region) where something like the following should appear:</p>
<pre><code>habitat,species,size,shape
humid,ustulatus,17.088,-0.029
humid,ustulatus,20.06,-0.001
humid,ustulatus,16.34,0.014
arid,calvus,13.734,-0.043
humid,nux,21.898,-0.042
humid,ustulatus,16.848,-0.023
humid,ustulatus,19.162,0.014
humid,ustulatus,16.017,0.042
arid,galapaganus,18.894,0.011
humid,nux,26.59,0</code></pre>
<p>And so on. Here the first row does not contain data, but instead contains the names of the different columns. Both the names in the first row and the data in subsequent ones are separated by a comma, which is our delimiter that separates information belonging in different columns. This also explains the strange-looking extension <code>.csv</code> to the file: this stands for <em>comma-separated values</em>. Comma-separated value files are some of the most often used ones in science, and we will be relying on them frequently throughout the book.</p>
</section>
<section id="sec-snail" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="sec-snail"><span class="header-section-number">4.2.2</span> The Galápagos land snail data</h3>
<p>It is worth explaining what the dataset in the file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-csv.zip"><code>island-FL.csv</code></a> represents, as we will be using it repeatedly in subsequent examples. Each row contains information on one land snail individual sampled from the Galápagos Islands. To simplify the data, the individuals have been restricted to just those that are from Floreana Island in the Galápagos. The columns in the data are:</p>
<ul>
<li><code>habitat</code>: This can be either “arid” or “humid”.</li>
<li><code>species</code>: Which species the individual belongs to. The Genus is always <em>Naesiotus</em>, from the family Bulimulidae. The seven species in the data are <em>Naesiotus calvus</em>, <em>N. galapaganus</em>, <em>N. invalidus</em>, <em>N. nux</em>, <em>N. rugulosus</em>, <em>N. unifasciatus</em>, and <em>N. ustulatus</em>.</li>
<li><code>size</code>: A measurement of the absolute volume of the snail’s shell. It is given in units we are not concerned with here, but larger values correspond to larger shells. See <span class="citation" data-cites="ParentCrespi2009">Parent and Crespi (<a href="99_References.html#ref-ParentCrespi2009" role="doc-biblioref">2009</a>)</span>, <span class="citation" data-cites="Kraemeretal2018">Kraemer et al. (<a href="99_References.html#ref-Kraemeretal2018" role="doc-biblioref">2018</a>)</span>, and <span class="citation" data-cites="Kraemeretal2022">Kraemer et al. (<a href="99_References.html#ref-Kraemeretal2022" role="doc-biblioref">2022</a>)</span> for more information.</li>
<li><code>shape</code>: A measurement for the shell’s shape. Again, the units are not important for us here, but small values represent bulky and round shells, while large values represent long and slender shells.</li>
</ul>
<p>Below are some pictures of these snails (courtesy of <a href="https://parentlab.weebly.com/">Dr.&nbsp;Christine E. Parent</a>):</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N-ustulatus.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><em>Naesiotus ustulatus</em> – a land snail from Floreana Island, Galápagos. Photo credits: Dr.&nbsp;Christine E. Parent.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N-ochsneri.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><em>N. ochsneri</em> – a land snail from Santa Cruz Island, Galápagos. Photo credits: Dr.&nbsp;Christine E. Parent.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N-chemnitzioides.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><em>N. chemnitzioides</em> – a land snail from San Cristóbal Island, Galápagos. Photo credits: Dr.&nbsp;Christine E. Parent.</figcaption>
</figure>
</div>
<p>Shell morphology is an important indicator of microhabitat specialization in these snails: species with long slender shells are adaptations to arid environments due to their better surface-to-volume ratios (see the picture of <em>N. chemnitzioides</em> above for an example), whereas species with round and bulky shells are better adapted to humid environments.</p>
</section>
<section id="tabulator-separated-and-other-delimited-files" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="tabulator-separated-and-other-delimited-files"><span class="header-section-number">4.2.3</span> Tabulator-separated and other delimited files</h3>
<p>Above we have discussed comma-separated files. Another type of file uses tabulators instead of commas as the column separator. These are called <em>tab-separated value</em> (TSV) files. Just like CSV files, TSV files are also very widely used. An example is provided by the file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-tsv.zip"><code>islands-FL.tsv</code></a>. The data in this file are exactly identical to the one in <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-csv.zip"><code>islands-FL.csv</code></a>. The only difference is that the commas are replaced by tabulators. Opening the file in RStudio, the first few lines look like this:</p>
<pre><code>habitat species size    shape
humid   ustulatus   17.088  -0.029
humid   ustulatus   20.06   -0.001
humid   ustulatus   16.34   0.014
arid    calvus  13.734  -0.043
humid   nux 21.898  -0.042
humid   ustulatus   16.848  -0.023
humid   ustulatus   19.162  0.014
humid   ustulatus   16.017  0.042
arid    galapaganus 18.894  0.011
humid   nux 26.59   0</code></pre>
<p>Commas and tabulators are not the only possible delimiters however, and in principle any character could play that role. The only thing to be wary of is that choosing some “regular” character as the delimiter might create unintended side effects. For instance, if the character <code>4</code> is the delimiter, then a number such as <code>0.143</code> will no longer be interpreted as a single number, but as two numbers in separate columns (<code>0.1</code> and <code>3</code>, respectively). For this reason, only those characters should be used as delimiters which we can be certain will never be confused with the actual data.</p>
<p>To give an example: it is perfectly possible and legal (even if not common) to use a “percent-separated value” representation where the symbol <code>%</code> is the delimiter. Here is what that would look like with the same land snail data (one can download it from <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-psv.zip"><code>islands-FL.psv</code></a>):</p>
<pre><code>habitat%species%size%shape
humid%ustulatus%17.088%-0.029
humid%ustulatus%20.06%-0.001
humid%ustulatus%16.34%0.014
arid%calvus%13.734%-0.043
humid%nux%21.898%-0.042
humid%ustulatus%16.848%-0.023
humid%ustulatus%19.162%0.014
humid%ustulatus%16.017%0.042
arid%galapaganus%18.894%0.011
humid%nux%26.59%0</code></pre>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The common file extensions <code>.csv</code> and <code>.tsv</code> are useful and suggestive: they can indicate that the data are comma- or tab-separated. However, one must bear in mind that these are mere naming conventions which are not forced in any way. That is, while not necessarily a good idea, it is perfectly possible to save comma-separated data in a file called <code>mydata.tsv</code>, or tab-separated data in <code>mydata.csv</code>. Furthermore, plain text files often have extensions such as <code>.txt</code> (“text”) or <code>.dat</code> (“data”), neither of which reveal what form the data were stored in. To be absolutely sure, one must open the file in a text editor such as RStudio’s top left editor panel, and see what was used as a delimiter. If you open a file like this, make absolutely sure not to modify and save it accidentally. Doing so compromises your hard-won data, which then no longer accurately capture your true observations.</p>
</div>
</div>
</section>
</section>
<section id="the-tibble-data-structure" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="the-tibble-data-structure"><span class="header-section-number">4.3</span> The <code>tibble</code> data structure</h2>
<p>The above raw formats are not yet amenable to processing within R. To make it so, we first need to import them. For delimited files there is a convenient function, <code>read_delim</code>, which makes this especially simple:<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>The function <code>read_delim</code> takes two inputs: the name of the file (with a path if needed), and <code>delim</code>, which is the delimiter used to separate the columns in the file. We will discuss how it works in greater detail in <a href="#sec-delim"><span>Section&nbsp;4.4</span></a>.</p>
<p>Look at the output that was produced by <code>read_delim("island-FL.csv", delim = ",")</code> above, starting with <code># A tibble: 223 x 4</code>. A <em>tibble</em> (or <em>data frame</em><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>) is the R-equivalent of an Excel-style spreadsheet. In this case, it has 223 rows and 4 columns (hence the <code>223 x 4</code>). The way to conceive of a tibble is as a collection of vectors, each arranged in a column, glued together side-by-side to form a table of data. Importantly, although each vector must consist of entries of the same type as usual (e.g., they can be vectors of numbers, vectors of strings, or vectors of logical values), the different columns need not share types. For example, in the above table, the first and second columns consist of character strings but the third and fourth ones consist of numerical values. This can be seen right below the header information. Below <code>habitat</code> and <code>species</code> you can see <code>&lt;chr&gt;</code>, which stands for “character string”. Below <code>size</code> and <code>shape</code> we have <code>&lt;dbl&gt;</code> which, confusing as it may look at first, refers simply to ordinary numbers.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> In turn, columns comprising of logical values would have the tag <code>&lt;lgl&gt;</code> underneath them (in this case though, we don’t have such a column). The point is that by looking at the type information below the header, you can see how R has interpreted each of the columns at a glance.</p>
<p>The fact that the individual columns are simply vectors can be made explicit, by relying on the <code>$</code>-notation. To access a given column of the table as a vector, we write the name of the table, followed by the <code>$</code> symbol, followed by the name of the column in question. To make the illustration easier, let us first assign the tibble to a variable called <code>snailDat</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>snailDat <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"island-FL.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now one can access e.g.&nbsp;the <code>size</code> column from the <code>snailDat</code> table as a vector of numbers like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>snailDat<span class="sc">$</span>size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 17.088 20.060 16.340 13.734 21.898 16.848 19.162 16.017 18.894 26.590
 [11] 17.865 13.857 21.706 15.354 21.369 22.714 16.530 16.604 16.292 16.075
 [21] 18.154 21.025 12.895 25.046 23.227 17.284 16.701 23.515 21.903 17.314
 [31] 23.891 21.349 24.946 14.122 28.467 17.010 16.831 16.641 20.244 22.042
 [41] 18.665 18.680 18.949 16.933 20.399 22.907 18.265 24.269 20.704 16.553
 [51] 19.246 24.894 23.610 14.131 15.617 18.605 18.343 19.340 17.017 16.868
 [61] 17.814 16.311 17.066 15.386 23.167 21.272 16.799 17.383 15.178 17.195
 [71] 19.027 15.011 23.723 17.569 20.091 18.773 22.885 13.661 33.792 19.390
 [81] 19.513 18.246 17.637 19.865 18.812 17.903 16.614 28.810 27.675 31.672
 [91] 17.209 21.618 26.420 19.135 20.493 15.142 17.195 17.382 15.502 14.404
[101] 22.678 16.210 30.946 14.347 14.541 20.546 20.994 20.103 31.923 24.465
[111] 24.451 19.188 20.610 16.193 15.989 25.314 16.610 13.507 16.744 21.330
[121] 20.480 19.246 19.125 18.642 18.250 17.152 18.814 21.081 15.852 16.743
[131] 16.602 14.879 12.299 21.646 20.539 21.798 19.211 18.168 24.985 19.938
[141] 20.176 14.846 23.488 24.120 17.320 16.118 18.924 15.928 15.478 21.282
[151] 15.838 19.506 24.212 18.066 17.427 15.213 20.748 20.504 20.311 17.444
[161] 20.846 19.351 18.679 24.111 17.906 16.322 21.967 15.992 22.788 17.920
[171] 18.804 24.760 25.766 23.452 16.145 16.040 18.868 17.528 16.556 22.199
[181] 24.424 18.800 21.335 20.191 19.225 23.424 15.601 27.679 29.221 20.373
[191] 16.037 17.577 21.852 18.969 16.933 19.290 24.102 21.398 16.369 19.649
[201] 25.137 18.394 23.102 32.001 16.946 19.054 18.527 18.646 21.361 14.362
[211] 15.858 17.201 19.886 19.264 21.503 21.728 23.312 20.423 21.912 18.158
[221] 16.859 20.488 22.369</code></pre>
</div>
</div>
<p>Here <code>snailDat$size</code> is really just a vector, and can be treated as such. For example, to get the 9th entry of this vector, we can use the usual bracket notation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>snailDat<span class="sc">$</span>size[<span class="dv">9</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.894</code></pre>
</div>
</div>
<p>The result is an ordinary numerical value.</p>
<p>Finally, let us take one more look at the output again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(snailDat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>When displaying large tibbles, R will not dump all the data at you. Instead, it will display the first 10 rows, with a message indicating how many more rows remain (in our case, we have <code>...with 213 more rows</code> written at the end of the printout). The system is still aware of the other rows; it just does not show them. To get a full view of a tibble in a more digestible, spreadsheet-like style, one can use the <code>view</code> function. Try running <code>view(snailDat)</code> and see what happens!</p>
</section>
<section id="sec-delim" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-delim"><span class="header-section-number">4.4</span> Reading delimited files</h2>
<p>We have seen that the function <code>read_delim</code> works by taking two inputs: the name of the file to read, and the delimiter character. So to read a comma-separated file, we can write</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>Similarly, in case we want to read a percent-separated file such as <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-psv.zip"><code>islands-FL.psv</code></a>, all we need to do is change the delimiter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL.psv"</span>, <span class="at">delim =</span> <span class="st">"%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>The output is exactly as before, since the file contained the same information (just represented differently due to the different delimiter).</p>
<p>To read a tab-separated file, remember <em>not</em> to simply press the tabulator key between the quotes of the <code>delim</code> argument. Instead, R uses the character string <code>"\t"</code> to represent a single press of the tabulator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL.tsv"</span>, <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>What happens if the wrong delimiter is specified—for instance, if we type <code>read_delim("island-FL.csv", delim = "%")</code>? In that case R will look for the <code>%</code> character to separate the columns, but since these do not occur anywhere, each row will be interpreted as a single column entry in its entirety:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL.csv"</span>, <span class="at">delim =</span> <span class="st">"%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 1
   `habitat,species,size,shape` 
   &lt;chr&gt;                        
 1 humid,ustulatus,17.088,-0.029
 2 humid,ustulatus,20.06,-0.001 
 3 humid,ustulatus,16.34,0.014  
 4 arid,calvus,13.734,-0.043    
 5 humid,nux,21.898,-0.042      
 6 humid,ustulatus,16.848,-0.023
 7 humid,ustulatus,19.162,0.014 
 8 humid,ustulatus,16.017,0.042 
 9 arid,galapaganus,18.894,0.011
10 humid,nux,26.59,0            
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>As seen, we have a tibble with a single column called <code>`habitat,species,size,shape1,shape2`</code>, which has the type <code>&lt;chr&gt;</code> (character string). One must beware of such mistakes, because the computer will not signal any errors: for all it cares, we <em>did</em> intend <code>%</code> to be the delimiter. However, one will not be able to properly work with the data subsequently if it gets loaded in this mistaken form.</p>
<p>The CSV and TSV file formats are so common that there are shorthands available for loading them. Instead of writing <code>read_delim("island-FL.csv", delim = ",")</code>, one can equivalently type <code>read_csv("island-FL.csv")</code> for the same effect:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="st">"island-FL.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>Similarly, <code>read_tsv("island-FL.tsv")</code> is an equivalent shorthand to <code>read_delim("island-FL.tsv", delim = "\t")</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_tsv</span>(<span class="st">"island-FL.tsv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
</section>
<section id="sec-rename" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-rename"><span class="header-section-number">4.5</span> Naming (and renaming) columns</h2>
<p>All of the files we have looked at so far contained a <em>header</em> as their first row: instead of containing data, they contained the names of the data columns. Having such a header is good practice. Sometimes however, the header may be missing. For example, the file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-nh.zip"><code>islands-FL-nohead.csv</code></a> contains the same land snail data as the other files above, but it lacks a header. The first few lines of the file look like this:</p>
<pre><code>humid,ustulatus,17.088,-0.029
humid,ustulatus,20.06,-0.001
humid,ustulatus,16.34,0.014
arid,calvus,13.734,-0.043
humid,nux,21.898,-0.042
humid,ustulatus,16.848,-0.023
humid,ustulatus,19.162,0.014
humid,ustulatus,16.017,0.042
arid,galapaganus,18.894,0.011
humid,nux,26.59,0</code></pre>
<p>If one tries to read this file either with <code>read_delim("island-FL-nohead.csv", delim = ",")</code> or the shorthand <code>read_csv("island-FL-nohead.csv")</code>, we get the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL-nohead.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 222 × 4
   humid ustulatus   `17.088` `-0.029`
   &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;
 1 humid ustulatus       20.1   -0.001
 2 humid ustulatus       16.3    0.014
 3 arid  calvus          13.7   -0.043
 4 humid nux             21.9   -0.042
 5 humid ustulatus       16.8   -0.023
 6 humid ustulatus       19.2    0.014
 7 humid ustulatus       16.0    0.042
 8 arid  galapaganus     18.9    0.011
 9 humid nux             26.6    0    
10 arid  calvus          17.9   -0.024
# ℹ 212 more rows</code></pre>
</div>
</div>
<p>The fact that a header is missing is obvious to a human reading the file—but not to the computer, which simply took the first row to be the header names anyway and interpreted the data in there as if they were column names. To avoid doing this, one can pass <code>col_names = FALSE</code> as an argument to either <code>read_delim</code>, <code>read_csv</code>, or <code>read_tsv</code>. The <code>col_names</code> argument is set by default to <code>TRUE</code>; to override it, we must explicitly change it like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL-nohead.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   X1    X2             X3     X4
   &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid ustulatus    17.1 -0.029
 2 humid ustulatus    20.1 -0.001
 3 humid ustulatus    16.3  0.014
 4 arid  calvus       13.7 -0.043
 5 humid nux          21.9 -0.042
 6 humid ustulatus    16.8 -0.023
 7 humid ustulatus    19.2  0.014
 8 humid ustulatus    16.0  0.042
 9 arid  galapaganus  18.9  0.011
10 humid nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>While this works, the column names now default to the moderately informative labels <code>X1</code>, <code>X2</code>, and so on. In fact, one can use the <code>col_names</code> argument to explicitly specify a vector of character strings, which are then interpreted as the names to be given to the columns in case no header information exists within the file itself. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_delim</span>(<span class="st">"island-FL-nohead.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">col_names =</span> <span class="fu">c</span>(<span class="st">"habitat"</span>, <span class="st">"species"</span>, <span class="st">"size"</span>, <span class="st">"shape"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>And now these data are identical to our earlier <code>snailDat</code> tibble.</p>
</section>
<section id="sec-excel" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="sec-excel"><span class="header-section-number">4.6</span> Excel tables</h2>
<p>Although their use is discouraged in science, one should know how to read data from an Excel spreadsheet. To do this, one needs to load the <code>readxl</code> package. This package is part of the <code>tidyverse</code>, but does not get automatically attached when running <code>library(tidyverse)</code>. Therefore, we first load the package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now load Excel files with the function <code>read_excel()</code>. At the start, we downloaded an Excel version of the land snail data, called <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/island-FL-xlsx.zip"><code>island-FL.xlsx</code></a>. It holds the exact same data as the original CSV file, just saved in Excel format for instructive purposes. Let us load this file:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="st">"island-FL.xlsx"</span>, <span class="at">sheet =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 223 × 4
   habitat species      size  shape
   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 humid   ustulatus    17.1 -0.029
 2 humid   ustulatus    20.1 -0.001
 3 humid   ustulatus    16.3  0.014
 4 arid    calvus       13.7 -0.043
 5 humid   nux          21.9 -0.042
 6 humid   ustulatus    16.8 -0.023
 7 humid   ustulatus    19.2  0.014
 8 humid   ustulatus    16.0  0.042
 9 arid    galapaganus  18.9  0.011
10 humid   nux          26.6  0    
# ℹ 213 more rows</code></pre>
</div>
</div>
<p>The <code>sheet</code> argument specifies which sheet of an Excel file we are importing (this file has only one of them, so technically the <code>sheet = 1</code> argument would have been optional). It can also be given as a character string, specifying the name of the sheet to be imported. The function <code>read_excel</code> has several further options as well—check its help page via <code>?read_excel</code> for more information.</p>
</section>
<section id="writing-data-to-files" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="writing-data-to-files"><span class="header-section-number">4.7</span> Writing data to files</h2>
<p>Finally, data can not only be read from a file, but also written out to one. Then, instead of <code>read_delim</code>, <code>read_csv</code>, <code>read_tsv</code> and the like, one uses <code>write_delim</code>, <code>write_csv</code>, <code>write_tsv</code>, and so on. For instance, to save some tibble called <code>dat</code> in CSV form, one can do either</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_delim</span>(dat, <span class="at">file =</span> <span class="st">"/path/to/file.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>or the equivalent but shorter</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(dat, <span class="at">file =</span> <span class="st">"/path/to/file.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where <code>/path/to/file.csv</code> should be replaced by the path and file name with which the data ought to be saved.</p>
</section>
<section id="sec-reading-exercises" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="sec-reading-exercises"><span class="header-section-number">4.8</span> Exercises</h2>
<ol type="1">
<li><span class="citation" data-cites="Goldbergetal2010">Goldberg et al. (<a href="99_References.html#ref-Goldbergetal2010" role="doc-biblioref">2010</a>)</span> collected data on self-incompatibility in the family Solanaceae (nightshades). It contains a list of 356 species, along with a column determining self-incompatibility status (0: self-incompatible; 1: self-compatible; 2-5: more complicated selfing scenarios). The data are in the file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/Goldberg2010_data-csv.zip"><code>Goldberg2010_data.csv</code></a>. An equivalent version is available in <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/Goldberg2010_data-xlsx.zip"><code>Goldberg2010_data.xlsx</code></a>, with the only difference that it is saved in Excel format.
<ul>
<li>Read the file <code>Goldberg2010_data.csv</code> using <code>read_delim</code>.</li>
<li>Read the file <code>Goldberg2010_data.csv</code> using <code>read_csv</code>.</li>
<li>Read the Excel file <code>Goldberg2010_data.xlsx</code> using <code>read_excel</code> from the <code>readxl</code> package.</li>
<li>Read the file <code>Goldberg2010_data.csv</code> using <code>read_csv</code>, and assign it to a variable called <code>goldbergDat</code>.</li>
<li>Extract the species names (first column, called <code>Species</code>) from <code>goldbergDat</code> as a vector of character strings, using the <code>$</code> notation. What are the 42nd and 137th entries of this vector?</li>
</ul></li>
<li>The data file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/ladybugs.zip"><code>ladybugs.csv</code></a> contains information on whether ladybugs sampled from rural versus industrial areas tend to be red or black morphs. Black morphs are thought to be an adaptation to more polluted industrial environments where the dark coloration provides better camouflage. The file is comma-separated and lacks headers. The meanings of the columns are, in order: habitat type, site code where the sampling was done, morph color, and the number of individuals sampled.
<ul>
<li>Load this file into a tibble in R, and give the following names to its columns: <code>habitat</code>, <code>site</code>, <code>morph</code>, and <code>number</code>.</li>
<li>Extract the last column (<code>number</code>) as a vector and calculate its mean and variance.</li>
</ul></li>
<li><span class="citation" data-cites="Smithetal2003">Smith et al. (<a href="99_References.html#ref-Smithetal2003" role="doc-biblioref">2003</a>)</span> compiled a database of the body masses of mammals of the late Quaternary period. The data are in the file <a href="https://raw.githubusercontent.com/dysordys/intro-R-and-stats/main/data/Smith2003_data.zip"><code>Smith2003_data.txt</code></a>. The column names are not specified in the file, but they are, in order: Continent (AF=Africa, etc.), Status (extinct, historical, introduction, or extant), Order, Family, Genus, Species, Base-10 Log Mass, Combined Mass (grams), and Reference (numbers, referring to a numerically ordered list of published works—no need to worry about the details).
<ul>
<li>What is the delimiter in this data file?</li>
<li>Load the data and give appropriate names to its columns, based on the information above.</li>
</ul></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Barabasetal2022" class="csl-entry" role="listitem">
Barabás, György, Christine Parent, Andrew Kraemer, Frederik Van de Perre, and Frederik De Laender. 2022. <span>“<span class="nocase">The evolution of trait variance creates a tension between species diversity and functional diversity</span>.”</span> <em>Nature Communications</em> 13 (2521): 1–10. <a href="https://doi.org/10.1038/s41467-022-30090-4">https://doi.org/10.1038/s41467-022-30090-4</a>.
</div>
<div id="ref-Goldbergetal2010" class="csl-entry" role="listitem">
Goldberg, Emma E., Joshua R. Kohn, Russell Lande, Kelly A. Robertson, Stephen A. Smith, and Boris Igić. 2010. <span>“<span>Species Selection Maintains Self-Incompatibility</span>.”</span> <em>Science</em> 330 (6003): 493–95. <a href="https://doi.org/10.1126/science.1194513">https://doi.org/10.1126/science.1194513</a>.
</div>
<div id="ref-Kraemeretal2018" class="csl-entry" role="listitem">
Kraemer, Andrew C., C. W. Philip, A. M. Rankin, and C. E. Parent. 2018. <span>“Trade-Offs Direct the Evolution of Coloration in <span>G</span>al<span>á</span>pagos Land Snails.”</span> <em>Proceedings of the Royal Society B</em> 286: 20182278.
</div>
<div id="ref-Kraemeretal2022" class="csl-entry" role="listitem">
Kraemer, Andrew C., Yannik E. Roell, Nate F. Shoobs, and Christine E. Parent. 2022. <span>“<span class="nocase">Does island ontogeny dictate the accumulation of both species richness and functional diversity?</span>”</span> <em>Global Ecology and Biogeography</em> 31 (1): 123–37. <a href="https://doi.org/10.1111/geb.13420">https://doi.org/10.1111/geb.13420</a>.
</div>
<div id="ref-ParentCrespi2009" class="csl-entry" role="listitem">
Parent, C. E., and B. J. Crespi. 2009. <span>“Ecological Opportunity in Adaptive Radiation of <span>Galápagos</span> Endemic Land Snails.”</span> <em>American Naturalist</em> 174: 898–905.
</div>
<div id="ref-Smithetal2003" class="csl-entry" role="listitem">
Smith, Felisa A., S. Kathleen Lyons, S. K. Morgan Ernest, Kate E. Jones, Dawn M. Kaufman, Tamar Dayan, Pablo A. Marquet, James H. Brown, and John P. Haskell. 2003. <span>“<span class="nocase">Body Mass of Late Quaternary Mammals</span>.”</span> <em>Ecology</em> 84 (12): 3403. <a href="https://doi.org/10.1890/02-9003">https://doi.org/10.1890/02-9003</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>If you are using a <code>tidyverse</code> version earlier than 2.0.0, only eight packages are loaded—<code>lubridate</code>, a package for working with dates, is missing from the list.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The data have been adapted from <span class="citation" data-cites="Barabasetal2022">Barabás et al. (<a href="99_References.html#ref-Barabasetal2022" role="doc-biblioref">2022</a>)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This and other data files used throughout the book will be accessible in a similar way. They are compressed in a zip file; extract them to obtain the data.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Warning: there exists a similarly-named function called <code>read.delim</code> which is part of base R. It does much the same thing as <code>read_delim</code>; however, its use is clunkier and less flexible. You can think of <code>read_delim</code> as the <code>tidyverse</code> upgrade to the original <code>read.delim</code>. My recommendation is to stick with using just <code>read_delim</code>—it is simpler and at the same time more powerful than its predecessor.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Data frames (a feature of base R) and tibbles (a <code>tidyverse</code> construct) are equivalent for most practical purposes. Tibbles offer some features that are absent from data frames and omit quirks of data frames which tend to get in the way. Like with <code>read_delim</code> and <code>read.delim</code>, tibbles can be thought of as a slightly upgraded and more user-friendly version of data frames. You do not need to be overly concerned with the precise differences between the two. In this book we will be using tibbles almost exclusively.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The abbreviation <code>&lt;dbl&gt;</code> happens to stand for <a href="https://en.wikipedia.org/wiki/Double-precision_floating-point_format">double-precision numerical value</a>, a standard way of representing numbers on computers.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_Functions.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Functions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_Basic_data_wrangling.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic data manipulation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>